language: python
python:
    - "3.8"

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip3 install -U platformio
    - platformio update

script:
    - cd "$TRAVIS_BUILD_DIR"
    - platformio run
